-- سوقي POS — Supabase PostgreSQL schema
-- Run this script in Supabase Dashboard > SQL Editor.
-- It creates the application tables only. It does not create or expose secrets.
-- The current app uses tenant-scoped numeric IDs and Manus OAuth openId values.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new."updatedAt" = now();
  return new;
end;
$$;

create table if not exists public.supermarkets (
  id integer generated by default as identity primary key,
  name varchar(180) not null,
  slug varchar(180) not null unique,
  phone varchar(40),
  address text,
  status varchar(32) not null default 'ACTIVE',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.branches (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  name varchar(160) not null,
  address text,
  phone varchar(40),
  status varchar(32) not null default 'ACTIVE',
  "createdAt" timestamptz not null default now()
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(128) not null unique,
  name text,
  email varchar(320),
  "loginMethod" varchar(64),
  role varchar(32) not null default 'OWNER',
  "supermarketId" integer references public.supermarkets(id) on delete set null,
  "branchId" integer references public.branches(id) on delete set null,
  permissions jsonb not null default '[]'::jsonb,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  "lastSignedIn" timestamptz not null default now()
);

create table if not exists public.subscription_plans (
  id integer generated by default as identity primary key,
  name varchar(80) not null,
  code varchar(32) not null unique,
  price numeric(12,2) not null default 0,
  "durationDays" integer not null default 30,
  "maxProducts" integer,
  "maxUsers" integer,
  "maxBranches" integer,
  "maxInvoices" integer,
  features jsonb not null default '[]'::jsonb,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  "planId" integer not null references public.subscription_plans(id) on delete restrict,
  status varchar(32) not null default 'ACTIVE',
  "startDate" timestamptz not null default now(),
  "endDate" timestamptz,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now()
);

create table if not exists public.categories (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  name varchar(120) not null,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  constraint categories_tenant_name_unique unique ("supermarketId", name)
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  "branchId" integer references public.branches(id) on delete set null,
  "categoryId" integer references public.categories(id) on delete set null,
  name varchar(200) not null,
  barcode varchar(80) not null,
  sku varchar(80),
  brand varchar(120),
  unit varchar(40) not null default 'قطعة',
  "sellingPrice" numeric(12,2) not null check ("sellingPrice" >= 0),
  "costPrice" numeric(12,2) not null default 0 check ("costPrice" >= 0),
  "stockQuantity" numeric(12,3) not null default 0 check ("stockQuantity" >= 0),
  "minimumStock" numeric(12,3) not null default 5 check ("minimumStock" >= 0),
  description text,
  "isActive" boolean not null default true,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz not null default now(),
  constraint products_tenant_barcode_unique unique ("supermarketId", barcode)
);

create table if not exists public.customers (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  name varchar(160) not null,
  phone varchar(40),
  address text,
  notes text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.invoices (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  "branchId" integer references public.branches(id) on delete set null,
  "cashierId" integer references public.users(id) on delete set null,
  "customerId" integer references public.customers(id) on delete set null,
  "invoiceNumber" varchar(80) not null unique,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  tax numeric(12,2) not null default 0 check (tax >= 0),
  total numeric(12,2) not null check (total >= 0),
  "paymentMethod" varchar(32) not null default 'CASH',
  status varchar(32) not null default 'PAID',
  "createdAt" timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id integer generated by default as identity primary key,
  "invoiceId" integer not null references public.invoices(id) on delete cascade,
  "productId" integer not null references public.products(id) on delete restrict,
  "productNameSnapshot" varchar(200) not null,
  "barcodeSnapshot" varchar(80) not null,
  "unitPrice" numeric(12,2) not null check ("unitPrice" >= 0),
  quantity numeric(12,3) not null check (quantity > 0),
  total numeric(12,2) not null check (total >= 0)
);

create table if not exists public.inventory_movements (
  id integer generated by default as identity primary key,
  "supermarketId" integer not null references public.supermarkets(id) on delete cascade,
  "branchId" integer references public.branches(id) on delete set null,
  "productId" integer not null references public.products(id) on delete restrict,
  "userId" integer references public.users(id) on delete set null,
  type varchar(32) not null,
  quantity numeric(12,3) not null,
  "previousQuantity" numeric(12,3) not null,
  "newQuantity" numeric(12,3) not null,
  reason text,
  "createdAt" timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id integer generated by default as identity primary key,
  "supermarketId" integer references public.supermarkets(id) on delete set null,
  "userId" integer references public.users(id) on delete set null,
  action varchar(120) not null,
  entity varchar(80) not null,
  "entityId" varchar(80),
  metadata jsonb not null default '{}'::jsonb,
  "createdAt" timestamptz not null default now()
);

create index if not exists users_tenant_idx on public.users ("supermarketId");
create index if not exists branches_tenant_idx on public.branches ("supermarketId");
create index if not exists subscriptions_tenant_idx on public.subscriptions ("supermarketId");
create index if not exists products_tenant_search_idx on public.products ("supermarketId", name);
create index if not exists customers_tenant_idx on public.customers ("supermarketId");
create index if not exists invoices_tenant_date_idx on public.invoices ("supermarketId", "createdAt");
create index if not exists invoice_items_invoice_idx on public.invoice_items ("invoiceId");
create index if not exists inventory_movements_tenant_date_idx on public.inventory_movements ("supermarketId", "createdAt");
create index if not exists audit_logs_date_idx on public.audit_logs ("createdAt");

-- Faster barcode and common catalog searches.
create index if not exists products_barcode_idx on public.products (barcode);
create index if not exists products_sku_idx on public.products (sku) where sku is not null;
create index if not exists customers_phone_idx on public.customers (phone) where phone is not null;

-- Keep updatedAt consistent with every update.
drop trigger if exists supermarkets_set_updated_at on public.supermarkets;
create trigger supermarkets_set_updated_at before update on public.supermarkets for each row execute function public.set_updated_at();
drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists plans_set_updated_at on public.subscription_plans;
create trigger plans_set_updated_at before update on public.subscription_plans for each row execute function public.set_updated_at();
drop trigger if exists subscriptions_set_updated_at on public.subscriptions;
create trigger subscriptions_set_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();
drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();

-- Starter plan used by first-login tenant provisioning.
insert into public.subscription_plans (name, code, price, "durationDays", "maxProducts", "maxUsers", "maxBranches", "maxInvoices", features)
values ('الخطة المجانية', 'FREE', 0, 30, 1000, 3, 1, 1000, '["pos", "inventory", "invoices"]'::jsonb)
on conflict (code) do nothing;

commit;

-- Security note:
-- The current server is the trusted API boundary and must use the server-only
-- Supabase connection string/secret. Never expose SUPABASE_SERVICE_ROLE_KEY,
-- SUPABASE_SECRET_KEY, SUPABASE_JWT_SECRET, or a database password to the browser.
-- Enable RLS policies after migrating the app authentication to Supabase Auth.
