CREATE TABLE "audit_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer,
	"userId" integer,
	"action" varchar(120) NOT NULL,
	"entity" varchar(80) NOT NULL,
	"entityId" varchar(80),
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "branches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "branches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"name" varchar(160) NOT NULL,
	"address" text,
	"phone" varchar(40),
	"status" varchar(32) DEFAULT 'ACTIVE' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"name" varchar(120) NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"name" varchar(160) NOT NULL,
	"phone" varchar(40),
	"address" text,
	"notes" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventory_movements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inventory_movements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"branchId" integer,
	"productId" integer NOT NULL,
	"userId" integer,
	"type" varchar(32) NOT NULL,
	"quantity" numeric(12, 3) NOT NULL,
	"previousQuantity" numeric(12, 3) NOT NULL,
	"newQuantity" numeric(12, 3) NOT NULL,
	"reason" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoice_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoice_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"invoiceId" integer NOT NULL,
	"productId" integer NOT NULL,
	"productNameSnapshot" varchar(200) NOT NULL,
	"barcodeSnapshot" varchar(80) NOT NULL,
	"unitPrice" numeric(12, 2) NOT NULL,
	"quantity" numeric(12, 3) NOT NULL,
	"total" numeric(12, 2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"branchId" integer,
	"cashierId" integer,
	"customerId" integer,
	"invoiceNumber" varchar(80) NOT NULL,
	"subtotal" numeric(12, 2) NOT NULL,
	"discount" numeric(12, 2) DEFAULT '0' NOT NULL,
	"tax" numeric(12, 2) DEFAULT '0' NOT NULL,
	"total" numeric(12, 2) NOT NULL,
	"paymentMethod" varchar(32) DEFAULT 'CASH' NOT NULL,
	"status" varchar(32) DEFAULT 'PAID' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_invoiceNumber_unique" UNIQUE("invoiceNumber")
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "products_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"branchId" integer,
	"categoryId" integer,
	"name" varchar(200) NOT NULL,
	"barcode" varchar(80) NOT NULL,
	"sku" varchar(80),
	"brand" varchar(120),
	"unit" varchar(40) DEFAULT 'قطعة' NOT NULL,
	"sellingPrice" numeric(12, 2) NOT NULL,
	"costPrice" numeric(12, 2) DEFAULT '0' NOT NULL,
	"stockQuantity" numeric(12, 3) DEFAULT '0' NOT NULL,
	"minimumStock" numeric(12, 3) DEFAULT '5' NOT NULL,
	"description" text,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subscription_plans" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscription_plans_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(80) NOT NULL,
	"code" varchar(32) NOT NULL,
	"price" numeric(12, 2) DEFAULT '0' NOT NULL,
	"durationDays" integer DEFAULT 30 NOT NULL,
	"maxProducts" integer,
	"maxUsers" integer,
	"maxBranches" integer,
	"maxInvoices" integer,
	"features" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "subscription_plans_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "subscriptions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subscriptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"supermarketId" integer NOT NULL,
	"planId" integer NOT NULL,
	"status" varchar(32) DEFAULT 'ACTIVE' NOT NULL,
	"startDate" timestamp with time zone DEFAULT now() NOT NULL,
	"endDate" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "supermarkets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supermarkets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(180) NOT NULL,
	"slug" varchar(180) NOT NULL,
	"phone" varchar(40),
	"address" text,
	"status" varchar(32) DEFAULT 'ACTIVE' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "supermarkets_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(128) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" varchar(32) DEFAULT 'OWNER' NOT NULL,
	"supermarketId" integer,
	"branchId" integer,
	"permissions" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE INDEX "audit_logs_date_idx" ON "audit_logs" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "branches_tenant_idx" ON "branches" USING btree ("supermarketId");--> statement-breakpoint
CREATE UNIQUE INDEX "categories_tenant_name_idx" ON "categories" USING btree ("supermarketId","name");--> statement-breakpoint
CREATE INDEX "customers_tenant_idx" ON "customers" USING btree ("supermarketId");--> statement-breakpoint
CREATE INDEX "inventory_movements_tenant_date_idx" ON "inventory_movements" USING btree ("supermarketId","createdAt");--> statement-breakpoint
CREATE INDEX "invoice_items_invoice_idx" ON "invoice_items" USING btree ("invoiceId");--> statement-breakpoint
CREATE INDEX "invoices_tenant_date_idx" ON "invoices" USING btree ("supermarketId","createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "products_tenant_barcode_idx" ON "products" USING btree ("supermarketId","barcode");--> statement-breakpoint
CREATE INDEX "products_tenant_search_idx" ON "products" USING btree ("supermarketId","name");--> statement-breakpoint
CREATE INDEX "subscriptions_tenant_idx" ON "subscriptions" USING btree ("supermarketId");--> statement-breakpoint
CREATE INDEX "users_tenant_idx" ON "users" USING btree ("supermarketId");