import { useMemo, useState } from "react";
import { BarChart3, Boxes, Building2, Check, CreditCard, Edit3, Search, ShieldCheck, Users, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type EditableProduct = { id: string; name: string; barcode: string; sellingPrice: number | string; isActive?: boolean };
const money = (value: number | string) => `${Number(value).toLocaleString("ar-EG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ج.م`;

function SectionTitle({ title, note }: { title: string; note?: string }) {
  return <div className="border-b border-[#e8efed] px-5 py-4"><h3 className="font-extrabold text-[#29464e]">{title}</h3>{note && <p className="mt-1 text-[11px] text-[#8a9c9c]">{note}</p>}</div>;
}

export function SuperAdminPanel() {
  const [productSearch, setProductSearch] = useState("");
  const [selectedProduct, setSelectedProduct] = useState<EditableProduct | null>(null);
  const [productName, setProductName] = useState("");
  const [productBarcode, setProductBarcode] = useState("");
  const [productPrice, setProductPrice] = useState("");
  const [storeNameDrafts, setStoreNameDrafts] = useState<Record<number, string>>({});
  const overview = trpc.superAdmin.overview.useQuery(undefined, { retry: false });
  const accounts = trpc.superAdmin.accounts.useQuery(undefined, { retry: false });
  const users = trpc.superAdmin.users.useQuery(undefined, { retry: false });
  const products = trpc.superAdmin.products.useQuery(undefined, { retry: false });
  const requests = trpc.superAdmin.priceChangeRequests.useQuery({ status: "PENDING" }, { retry: false });
  const platformInvoices = trpc.superAdmin.invoices.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const refreshAdmin = () => {
    void utils.superAdmin.overview.invalidate();
    void utils.superAdmin.accounts.invalidate();
    void utils.superAdmin.users.invalidate();
    void utils.superAdmin.products.invalidate();
    void utils.superAdmin.priceChangeRequests.invalidate();
    void utils.superAdmin.invoices.invalidate();
  };
  const review = trpc.superAdmin.reviewPriceChange.useMutation({ onSuccess: result => { toast.success(result.status === "APPROVED" ? "تم اعتماد السعر الجديد ونشره للجميع" : "تم رفض طلب السعر"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const saveProduct = trpc.superAdmin.updateProduct.useMutation({ onSuccess: () => { toast.success("تم تحديث المنتج العام"); setSelectedProduct(null); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const setProductActive = trpc.superAdmin.setProductActive.useMutation({ onSuccess: () => { toast.success("تم تحديث ظهور المنتج"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const setRole = trpc.superAdmin.setUserRole.useMutation({ onSuccess: () => { toast.success("تم تحديث دور الحساب"); void users.refetch(); }, onError: error => toast.error(error.message) });
  const setActive = trpc.superAdmin.setUserActive.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الحساب"); void users.refetch(); }, onError: error => toast.error(error.message) });
  const setUserName = trpc.superAdmin.updateUserName.useMutation({ onSuccess: () => { toast.success("تم تحديث اسم الحساب"); void users.refetch(); }, onError: error => toast.error(error.message) });
  const setSubscription = trpc.superAdmin.setSubscription.useMutation({ onSuccess: () => { toast.success("تم تحديث الاشتراك"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const setPaymentStatus = trpc.superAdmin.setSubscriptionPaymentStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الدفع"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const updateStore = trpc.superAdmin.updateStore.useMutation({ onSuccess: () => { toast.success("تم تحديث بيانات المتجر"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const setInvoiceStatus = trpc.superAdmin.setInvoiceStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الفاتورة"); refreshAdmin(); }, onError: error => toast.error(error.message) });
  const filteredProducts = useMemo(() => (products.data ?? []).filter(product => !productSearch || `${product.name} ${product.barcode}`.toLocaleLowerCase().includes(productSearch.toLocaleLowerCase())), [productSearch, products.data]);

  const openEditProduct = (product: EditableProduct) => {
    setSelectedProduct(product);
    setProductName(product.name);
    setProductBarcode(product.barcode);
    setProductPrice(String(product.sellingPrice));
  };
  const saveProductForm = (event: React.FormEvent) => {
    event.preventDefault();
    if (!selectedProduct) return;
    saveProduct.mutate({ id: selectedProduct.id, name: productName.trim(), barcode: productBarcode.trim(), sellingPrice: Number(productPrice) });
  };
  const saveStoreName = (store: { id: number; name: string; phone?: string | null; address?: string | null }) => {
    const name = (storeNameDrafts[store.id] ?? store.name).trim();
    if (name.length < 2) { toast.error("اسم المتجر قصير جدًا."); return; }
    updateStore.mutate({ supermarketId: store.id, name, phone: store.phone ?? null, address: store.address ?? null });
  };

  const metrics = overview.data;
  const cards = [
    { label: "المتاجر", value: metrics?.supermarkets ?? "—", icon: <Building2 size={18} /> },
    { label: "الحسابات", value: metrics?.users ?? "—", icon: <Users size={18} /> },
    { label: "المنتجات المشتركة", value: metrics?.products ?? "—", icon: <Boxes size={18} /> },
    { label: "المبيعات المسجلة", value: money(metrics?.sales ?? 0), icon: <BarChart3 size={18} /> },
    { label: "مبيعات اليوم", value: money(metrics?.todaySales ?? 0), icon: <BarChart3 size={18} /> },
    { label: "فواتير اليوم", value: metrics?.todayInvoices ?? "—", icon: <CreditCard size={18} /> },
    { label: "مبيعات الشهر", value: money(metrics?.monthSales ?? 0), icon: <BarChart3 size={18} /> },
    { label: "اشتراكات مدفوعة نشطة", value: metrics?.paidSubscriptions ?? "—", icon: <CreditCard size={18} /> },
    { label: "اشتراكات غير مدفوعة / تجريبية", value: metrics?.unpaidSubscriptions ?? "—", icon: <CreditCard size={18} /> },
  ];

  return <div className="space-y-5">
    <div className="rounded-2xl bg-[#071723] p-6 text-white"><div className="flex items-center gap-2 text-xs font-bold text-[#b8efdc]"><ShieldCheck size={15} /> تحكم المنصة</div><h2 className="mt-2 text-2xl font-extrabold">لوحة الإدارة العليا</h2><p className="mt-1 text-xs text-[#94afb1]">إدارة الكتالوج العالمي، مراجعة الأسعار، الحسابات وحالة الاشتراكات.</p><p className="mt-2 text-[10px] text-[#b8efdc]">إحصاءات المدفوع وغير المدفوع تعتمد على حالة الدفع التي يسجلها المدير يدويًا بعد التحقق؛ لا تُنفذ المنصة تحصيلًا ماليًا تلقائيًا.</p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cards.map(card => <div key={card.label} className="rounded-2xl border border-[#e0e9e6] bg-white p-4"><div className="flex items-center gap-2 text-[#267a60]">{card.icon}<span className="text-[11px] font-bold text-[#73888a]">{card.label}</span></div><div className="mt-3 text-2xl font-extrabold text-[#29464e]">{card.value}</div></div>)}<div className="rounded-2xl border border-[#f1d99b] bg-[#fff9e8] p-4"><div className="text-[11px] font-bold text-[#8c690f]">طلبات الأسعار بانتظار المراجعة</div><div className="mt-3 text-2xl font-extrabold text-[#725100]">{metrics?.pendingPriceChanges ?? requests.data?.length ?? "—"}</div></div></div>

    <section className="overflow-hidden rounded-2xl border border-[#e0e9e6] bg-white"><SectionTitle title="طلبات تغيير الأسعار" note="السعر العام لا يتغير إلا بعد اعتماد مدير الموقع." />{requests.isLoading ? <div className="p-8 text-center text-xs text-[#829394]">جارٍ تحميل الطلبات...</div> : requests.data?.length ? <div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-[#f8fbfa] text-[10px] font-extrabold text-[#88999a]"><tr><th className="px-4 py-3">المنتج والباركود</th><th className="px-4 py-3">السعر الحالي</th><th className="px-4 py-3">المقترح</th><th className="px-4 py-3">مقدم الطلب</th><th className="px-4 py-3">الإجراء</th></tr></thead><tbody>{requests.data.map(request => <tr key={request.id} className="border-t border-[#eef3f1]"><td className="px-4 py-3"><strong className="block text-[#34515a]">{request.productName}</strong><span className="mono text-[10px] text-[#829394]">{request.barcode}</span></td><td className="px-4 py-3">{money(request.currentPrice)}</td><td className="px-4 py-3 font-extrabold text-[#0f6e58]">{money(request.proposedPrice)}</td><td className="px-4 py-3">{request.submittedByName}</td><td className="px-4 py-3"><div className="flex gap-2"><button disabled={review.isPending} onClick={() => review.mutate({ requestId: request.id, status: "APPROVED" })} className="rounded-lg bg-[#e7f6f0] px-2.5 py-1.5 font-bold text-[#267a60]">اعتماد</button><button disabled={review.isPending} onClick={() => review.mutate({ requestId: request.id, status: "REJECTED" })} className="rounded-lg bg-[#fce8e7] px-2.5 py-1.5 font-bold text-[#a83d42]">رفض</button></div></td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-xs text-[#829394]">لا توجد طلبات معلقة.</div>}</section>

    <section className="overflow-hidden rounded-2xl border border-[#e0e9e6] bg-white"><SectionTitle title="الكتالوج العالمي" note="المنتجات والباركود والسعر المشترك لجميع المستخدمين؛ لا توجد كميات أو ميزان." /><div className="border-b border-[#eef3f1] p-4"><div className="relative max-w-sm"><Search className="absolute right-3 top-1/2 -translate-y-1/2 text-[#93a3a3]" size={15} /><input value={productSearch} onChange={event => setProductSearch(event.target.value)} placeholder="بحث بالاسم أو الباركود" className="w-full rounded-xl border border-[#dfe9e5] bg-[#f8fbfa] py-2.5 pr-9 pl-3 text-xs outline-none" /></div></div>{products.isLoading ? <div className="p-8 text-center text-xs text-[#829394]">جارٍ تحميل المنتجات...</div> : <div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-[#f8fbfa] text-[10px] font-extrabold text-[#88999a]"><tr><th className="px-4 py-3">المنتج</th><th className="px-4 py-3">الباركود</th><th className="px-4 py-3">السعر المعتمد</th><th className="px-4 py-3">الحالة</th><th className="px-4 py-3">تحكم</th></tr></thead><tbody>{filteredProducts.map(product => <tr key={product.id} className="border-t border-[#eef3f1]"><td className="px-4 py-3 font-extrabold text-[#34515a]">{product.name}</td><td className="mono px-4 py-3 text-[#819293]">{product.barcode}</td><td className="px-4 py-3 font-bold">{money(product.sellingPrice)}</td><td className="px-4 py-3">{product.isActive === false ? "موقوف" : "نشط"}</td><td className="px-4 py-3"><div className="flex gap-2"><button onClick={() => openEditProduct(product)} className="inline-flex items-center gap-1 rounded-lg border border-[#dbe5e1] px-2 py-1.5 font-bold text-[#526c70]"><Edit3 size={13} /> تعديل</button><button onClick={() => setProductActive.mutate({ productId: product.id, isActive: product.isActive === false })} className="rounded-lg bg-[#f3f6f5] px-2 py-1.5 font-bold text-[#526c70]">{product.isActive === false ? "تفعيل" : "إيقاف"}</button></div></td></tr>)}</tbody></table>{!filteredProducts.length && <div className="p-8 text-center text-xs text-[#829394]">لا توجد نتائج.</div>}</div>}</section>

    <section className="overflow-hidden rounded-2xl border border-[#e0e9e6] bg-white"><SectionTitle title="المتاجر والاشتراكات" note="تجديد الاشتراك أو إيقافه، وتعديل بيانات المتجر وتسجيل الدفع بعد التحقق اليدوي." />{accounts.isLoading ? <div className="p-8 text-center text-xs text-[#829394]">جارٍ تحميل المتاجر...</div> : <div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-[#f8fbfa] text-[10px] font-extrabold text-[#88999a]"><tr><th className="px-3 py-3">المتجر</th><th className="px-3 py-3">الاشتراك</th><th className="px-3 py-3">الانتهاء</th><th className="px-3 py-3">تحكم</th></tr></thead><tbody>{accounts.data?.map(({ store, access }) => <tr key={store.id} className="border-t border-[#eef3f1]"><td className="px-3 py-3"><input value={storeNameDrafts[store.id] ?? store.name} onChange={event => setStoreNameDrafts(current => ({ ...current, [store.id]: event.target.value }))} className="w-40 rounded-md border border-transparent bg-transparent px-1 py-1 font-extrabold text-[#34515a] focus:border-[#dbe5e1]" /><button onClick={() => saveStoreName(store as { id: number; name: string; phone?: string | null; address?: string | null })} className="mr-2 rounded-md bg-[#edf7f3] px-2 py-1 text-[10px] font-bold text-[#267a60]">حفظ الاسم</button></td><td className="px-3 py-3">{access?.isActive ? <span className="rounded-full bg-[#e7f6f0] px-2 py-1 text-[10px] font-bold text-[#2a8064]">نشط</span> : <span className="rounded-full bg-[#fce8e7] px-2 py-1 text-[10px] font-bold text-[#a83d42]">منتهي / موقوف</span>}<select aria-label="حالة الدفع" value={access?.subscription?.paymentStatus === "PAID" ? "PAID" : "UNPAID"} onChange={event => setPaymentStatus.mutate({ supermarketId: store.id, paymentStatus: event.target.value as "PAID" | "UNPAID" })} className="mr-2 rounded-lg border border-[#dfe9e5] bg-white px-2 py-1 text-[10px]"><option value="PAID">مدفوع</option><option value="UNPAID">غير مدفوع</option></select></td><td className="px-3 py-3 text-[#76888a]">{access?.effectiveEnd ? new Date(access.effectiveEnd).toLocaleDateString("ar-EG") : "—"}</td><td className="px-3 py-3"><div className="flex gap-2"><button onClick={() => setSubscription.mutate({ supermarketId: store.id, status: "ACTIVE", endDate: new Date(Date.now() + 30 * 86400000) })} className="rounded-lg bg-[#e7f5f0] px-2 py-1.5 text-[10px] font-bold text-[#267a60]">تمديد 30 يومًا</button><button onClick={() => setSubscription.mutate({ supermarketId: store.id, status: "PAUSED", endDate: access?.effectiveEnd ? new Date(access.effectiveEnd) : null })} className="rounded-lg bg-[#fce8e7] px-2 py-1.5 text-[10px] font-bold text-[#a83d42]">إيقاف</button></div></td></tr>)}</tbody></table></div>}</section>

    <section className="overflow-hidden rounded-2xl border border-[#e0e9e6] bg-white"><SectionTitle title="الحسابات والأدوار" note="تعديل اسم العرض والدور أو تعطيل الحساب." />{users.isLoading ? <div className="p-8 text-center text-xs text-[#829394]">جارٍ تحميل الحسابات...</div> : <div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-[#f8fbfa] text-[10px] font-extrabold text-[#88999a]"><tr><th className="px-3 py-3">الاسم والبريد</th><th className="px-3 py-3">الدور</th><th className="px-3 py-3">المتجر</th><th className="px-3 py-3">الحالة</th><th className="px-3 py-3">إجراء</th></tr></thead><tbody>{users.data?.map(user => <tr key={user.id} className="border-t border-[#eef3f1]"><td className="px-3 py-3"><div className="flex gap-1"><input defaultValue={user.name || ""} id={`name-${user.id}`} className="w-36 rounded-md border border-[#e6edeb] px-2 py-1 font-bold" /><button onClick={() => { const element = document.getElementById(`name-${user.id}`) as HTMLInputElement | null; if (element) setUserName.mutate({ userId: user.id, name: element.value }); }} className="rounded-md bg-[#edf7f3] px-2 text-[10px] font-bold text-[#267a60]">حفظ</button></div><div className="mt-1 text-[10px] text-[#899b9b]">{user.email || "—"}</div></td><td className="px-3 py-3"><select value={user.role} onChange={event => setRole.mutate({ userId: user.id, role: event.target.value as "OWNER" | "ADMIN" | "MANAGER" | "CASHIER" })} className="rounded-lg border border-[#dfe9e5] bg-white px-2 py-1"><option value="OWNER">OWNER</option><option value="ADMIN">ADMIN</option><option value="MANAGER">MANAGER</option><option value="CASHIER">CASHIER</option><option value="SUPER_ADMIN" disabled>SUPER_ADMIN (منح عبر UID موثوق)</option></select></td><td className="px-3 py-3">{user.supermarketId ?? "—"}</td><td className="px-3 py-3">{user.isActive ? "نشط" : "موقوف"}</td><td className="px-3 py-3"><button onClick={() => setActive.mutate({ userId: user.id, isActive: !user.isActive })} className="rounded-lg border border-[#dfe9e5] px-2 py-1.5 font-bold text-[#526c70]">{user.isActive ? "تعطيل" : "تفعيل"}</button></td></tr>)}</tbody></table></div>}</section>

    <section className="overflow-hidden rounded-2xl border border-[#e0e9e6] bg-white"><SectionTitle title="فواتير المنصة" note="عرض أحدث الفواتير من جميع المتاجر وإدارة حالتها." />{platformInvoices.isLoading ? <div className="p-8 text-center text-xs text-[#829394]">جارٍ تحميل الفواتير...</div> : platformInvoices.data?.length ? <div className="overflow-x-auto"><table className="w-full text-right text-xs"><thead className="bg-[#f8fbfa] text-[10px] font-extrabold text-[#88999a]"><tr><th className="px-3 py-3">رقم الفاتورة</th><th className="px-3 py-3">المتجر</th><th className="px-3 py-3">التاريخ</th><th className="px-3 py-3">الإجمالي</th><th className="px-3 py-3">الحالة</th></tr></thead><tbody>{platformInvoices.data.slice(0, 200).map(invoice => <tr key={invoice.id} className="border-t border-[#eef3f1]"><td className="mono px-3 py-3 font-bold text-[#34515a]">{invoice.invoiceNumber}</td><td className="px-3 py-3">#{invoice.supermarketId}</td><td className="px-3 py-3 text-[#76888a]">{new Date(invoice.createdAt).toLocaleString("ar-EG")}</td><td className="px-3 py-3 font-extrabold">{money(invoice.total)}</td><td className="px-3 py-3"><select value={invoice.status} onChange={event => setInvoiceStatus.mutate({ invoiceId: invoice.id, status: event.target.value as "PAID" | "VOID" | "REFUNDED" })} className="rounded-lg border border-[#dfe9e5] bg-white px-2 py-1"><option value="PAID">مدفوعة</option><option value="VOID">ملغاة</option><option value="REFUNDED">مستردة</option></select></td></tr>)}</tbody></table></div> : <div className="p-8 text-center text-xs text-[#829394]">لا توجد فواتير بعد.</div>}</section>

    {selectedProduct && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-[#031018]/75 p-4" dir="rtl"><form onSubmit={saveProductForm} className="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h3 className="text-lg font-extrabold text-[#193a40]">تعديل منتج عام</h3><button type="button" onClick={() => setSelectedProduct(null)} aria-label="إغلاق"><X size={20} /></button></div><label className="mt-4 block text-xs font-bold text-[#597175]">اسم المنتج<input required minLength={2} value={productName} onChange={event => setProductName(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#dfe9e5] px-3 py-3" /></label><label className="mt-3 block text-xs font-bold text-[#597175]">الباركود<input required minLength={3} value={productBarcode} onChange={event => setProductBarcode(event.target.value)} className="mono mt-1.5 w-full rounded-xl border border-[#dfe9e5] px-3 py-3" /></label><label className="mt-3 block text-xs font-bold text-[#597175]">السعر المعتمد<input required min="0" step="0.01" type="number" value={productPrice} onChange={event => setProductPrice(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#dfe9e5] px-3 py-3" /></label><button disabled={saveProduct.isPending} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f5d4d] py-3 font-extrabold text-white"><Check size={15} /> حفظ التعديل</button></form></div>}
  </div>;
}
